module Routes.PetInfoPage exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Types exposing (..)


petInfoPage : Model -> Html Msg
petInfoPage model =
    div [ class "ma3" ]
        [ div [ class " blue b mb2" ] [ text "What is your pets name?" ]
        , div []
            [ input [ type_ "text", class "bg-light-blue w-80 br2 pa3 gray bn" ]
                [ text "" ]
            ]
        , div [ class "gray f6 fw1" ] [ text "Please enter your pets name" ]
        , div [ class " blue b mb2 mt4" ] [ text "What pet do you have?" ]
        , div [ class "m0-auto tc" ]
            [ img [ src "./assets/circle-images.svg" ] []
            ]
        , div []
            [ div [ class "blue b mb2 mt4" ] [ text "What Breed is your dog?" ]
            , div []
                [ select [ class "bg-light-blue bn w-80 gray tc pa3 mb3 f5 fw1" ]
                    [ option [ value "Please choose" ]
                        [ text "Please Choose" ]
                    , option [ value "Labrador" ]
                        [ text "Labrador" ]
                    ]
                ]
            ]
        , div []
            [ div [ class "gray f6 fw1" ] [ text "Other:" ]
            , div []
                [ input [ type_ "text", class "bg-light-blue w-80 br2 pa3 gray bn" ]
                    []
                ]
            ]
        , div [ class "blue b mb2 mt4" ] [ text "How old is Rex?" ]
        , div [ class "m0-aut0 tc" ]
            [ div [ class "fl w-50" ]
                [ button [ class "bg-blue w-80 white pa3 fw1 br2 mb3" ] [ text "0-1 Year" ]
                ]
            , div [ class "fl w-50" ]
                [ button [ class "bg-blue w-80 white pa3 fw1 br2 mb3" ] [ text "1-3 Years" ]
                ]
            ]
        , div [ class "m0-auto tc" ]
            [ div [ class "fl w-50" ]
                [ button [ class "bg-blue w-80 white pa3 fw1 br2 mb4" ] [ text "3-6 Years" ]
                ]
            , div [ class "fl w-50" ]
                [ button [ class "bg-blue w-80 white pa3 fw1 br2 mb4" ] [ text "6+ Years" ]
                ]
            ]
        , div [ class "mt4 tc w-100" ]
            [ a [ class "w-100 bg-navy br2 white pa3 br2 f4 dib", href "#before-you-begin" ] [ text "Next" ]
            ]
        ]
